### ISSUE TITLE
一些改进意见

### ISSUE THREAD

**Issue by lowbees** [xtuer/app-template#1]
1.在.pro设置DESTDIR     = $$PWD/bin，这样直接在bin目录下生成exe，不用拷贝bin目录了
2.为QComboBox的弹出框增加qss支持
```
QList<QComboBox *> cbList = cw->findChildren<QComboBox*>();
    foreach (QComboBox *cb, cbList)
        cb->setView(new QListView);
```

**Comment by xtuer** [comment]
1. 在.pro设置DESTDIR = $$PWD/bin，这样直接在bin目录下生成exe，不用拷贝bin目录了
打包是需要复制文件到 bin 文件夹，会导致 git 状态变化

2. 为QComboBox的弹出框增加qss支持
不用这么麻烦，看 boxbar.qss 里，QSS 支持的
QComboBox QAbstractItemView {
    margin-top: 0px;
    padding-bottom: 0px;
    border: 1px solid #FFF;
    border-radius: 4px;
    background-color: white;
}
